import sunburnHoodieAcidBlack from "@/assets/clothes/hoodies/sunburn-hoodie-acid-black.webp";
import blessednLostLsAcidBlack from "@/assets/clothes/longsleeves/blessedn-lost-ls-acid-black.jpg";
import aquaBoxTeeVintageWhite from "@/assets/clothes/tees/aqua-box-tee-vintage-white.jpg";
import waveTigerTeePinkKush from "@/assets/clothes/tees/wave-tiger-tee-pink-kush.webp";
import { Clothes } from "./types";

export const TEES: Clothes[] = [
  {
    id: "T1",
    name: "Wave Tiger Tee - Pink Kush",
    images: [waveTigerTeePinkKush],
    price: "62",
    description: "",
    bestseller: true,
  },
  {
    id: "T2",
    name: "Aqua Box Tee - Vintage White",
    images: [aquaBoxTeeVintageWhite],
    price: "50",
    description: "",
    bestseller: true,
  },
  {
    id: "T3",
    name: "Sunburn Tee - Super Natural",
    images: [aquaBoxTeeVintageWhite],
    price: "60",
    description: "",
    bestseller: true,
  },
  {
    id: "T4",
    name: "No Rules Tee - Paper White",
    images: [aquaBoxTeeVintageWhite],
    price: "60",
    description: "",
    bestseller: false,
  },
  {
    id: "T5",
    name: "Joints & Surf Tee - Super Natural",
    images: [aquaBoxTeeVintageWhite],
    price: "60",
    description: "",
    bestseller: true,
  },
  {
    id: "T6",
    name: "Own Business Tee - Super Natural",
    images: [aquaBoxTeeVintageWhite],
    price: "60",
    description: "",
    bestseller: false,
  },
  {
    id: "T7",
    name: "Potato Wave Tee - Super Natural",
    images: [aquaBoxTeeVintageWhite],
    price: "60",
    description: "",
    bestseller: false,
  },
  {
    id: "T8",
    name: "CH6 Tee - Vintage White",
    images: [aquaBoxTeeVintageWhite],
    price: "48",
    description: "",
    bestseller: false,
  },
  {
    id: "T9",
    name: "Wave Tiger Tee - Purple Haze",
    images: [aquaBoxTeeVintageWhite],
    price: "62",
    description: "",
    bestseller: false,
  },
  {
    id: "T10",
    name: "Surf People Tee - Vintage White",
    images: [aquaBoxTeeVintageWhite],
    price: "48",
    description: "",
    bestseller: false,
  },
  {
    id: "T11",
    name: "Power Flower Tee - Dirty White",
    images: [aquaBoxTeeVintageWhite],
    price: "62",
    description: "",
    bestseller: false,
  },
  {
    id: "T12",
    name: "Trippin' Tee - Pink Kush",
    images: [aquaBoxTeeVintageWhite],
    price: "60",
    description: "",
    bestseller: false,
  },
  {
    id: "T13",
    name: "Do Nothing Club Tee - Acid Black",
    images: [aquaBoxTeeVintageWhite],
    price: "80",
    description: "",
    bestseller: false,
  },
];

export const HOODIES: Clothes[] = [
  {
    id: "H1",
    name: "Sunburn Hoodie - Acid Black",
    images: [sunburnHoodieAcidBlack],
    price: "92",
    description: "",
    bestseller: true,
  },
  {
    id: "H2",
    name: "Aqua Sweat - Vintage White",
    images: [aquaBoxTeeVintageWhite],
    price: "80",
    description: "",
    bestseller: true,
  },
  {
    id: "H3",
    name: "Power Flower Sweat - Pink Kush",
    images: [aquaBoxTeeVintageWhite],
    price: "80",
    description: "",
    bestseller: true,
  },
  {
    id: "H4",
    name: "Organic Wave Sweat - Vintage White",
    images: [aquaBoxTeeVintageWhite],
    price: "80",
    description: "",
    bestseller: true,
  },
  {
    id: "H5",
    name: "CH6 Hoodie - Cookie",
    images: [aquaBoxTeeVintageWhite],
    price: "92",
    description: "",
    bestseller: false,
  },
  {
    id: "H6",
    name: "CH6 Hoodie - Acid Black",
    images: [aquaBoxTeeVintageWhite],
    price: "92",
    description: "",
    bestseller: false,
  },
  {
    id: "H7",
    name: "Surf Star Hoodie - Vintage White",
    images: [aquaBoxTeeVintageWhite],
    price: "103",
    description: "",
    bestseller: false,
  },
  {
    id: "H8",
    name: "Play N'Pray Hoodie - Vintage White",
    images: [aquaBoxTeeVintageWhite],
    price: "103",
    description: "",
    bestseller: false,
  },
  {
    id: "H9",
    name: "Mad Company Sweat - Acid Black",
    images: [aquaBoxTeeVintageWhite],
    price: "80",
    description: "",
    bestseller: false,
  },
  {
    id: "H10",
    name: "Wine And Surf Sweat - Vintage White",
    images: [aquaBoxTeeVintageWhite],
    price: "85",
    description: "",
    bestseller: false,
  },
];

export const LONGSLEEVES: Clothes[] = [
  {
    id: "L1",
    name: "Blessedn' Lost LS - Acid Black",
    images: [blessednLostLsAcidBlack],
    price: "92",
    description: "",
    bestseller: false,
  },
  {
    id: "L2",
    name: "Party Wave LS - Pink Kush",
    images: [aquaBoxTeeVintageWhite],
    price: "92",
    description: "",
    bestseller: false,
  },
  {
    id: "L3",
    name: "Cobra Grip LS - Acid Black",
    images: [aquaBoxTeeVintageWhite],
    price: "92",
    description: "",
    bestseller: false,
  },
  {
    id: "L4",
    name: "Sea Lions LS - Dirty White",
    images: [aquaBoxTeeVintageWhite],
    price: "69",
    description: "",
    bestseller: true,
  },
  {
    id: "L5",
    name: "Starfish LS - Dirty White",
    images: [aquaBoxTeeVintageWhite],
    price: "69",
    description: "",
    bestseller: false,
  },
  {
    id: "L6",
    name: "No Rules LS - Brownie",
    images: [aquaBoxTeeVintageWhite],
    price: "69",
    description: "",
    bestseller: true,
  },
  {
    id: "L7",
    name: "Sunburn LS - Optic White",
    images: [aquaBoxTeeVintageWhite],
    price: "69",
    description: "",
    bestseller: true,
  },
  {
    id: "L8",
    name: "Salty Dreams LS - Vintage White",
    images: [aquaBoxTeeVintageWhite],
    price: "57",
    description: "",
    bestseller: false,
  },
];
