services:
  - type: web
    name: surfapp
    env: node
    plan: free
    buildCommand:
      npm install --prod=false &&
      blitz prisma generate &&
      blitz build &&
      blitz prisma migrate deploy
    startCommand: blitz start -p ${PORT}
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: surfapp-db
          property: connectionString
      - key: SESSION_SECRET_KEY
        generateValue: true
      - key: APP_ORIGIN
        value: https://surfapp-ggrv.onrender.com

databases:
  - name: surfapp-db
    plan: free