import type {Metadata} from "next";
import {Poppins} from "next/font/google";
import "@/styles/globals.css";

import {cn} from "@/lib/utils";
import Header from "@/components/header/header";
import Footer from "@/components/footer/footer";
import {Toaster} from "@/components/ui/toaster";
import PageWrapper from "@/components/wrapper/page-wrapper";

const poppins = Poppins({
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-poppins',
    weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={cn(
                "min-h-screen bg-background text-primary font-poppins tracking-widest antialiased",
                poppins.variable
            )}
        >
        <Header/>
        <PageWrapper>
            {children}
        </PageWrapper>
        <Footer/>
        <Toaster/>
        </body>
        </html>
    );
}
